config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
   devise_scope :user do
     get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroyy_user_session
   end

  resources :photos do
    resources :comments
    resources :likes

    member do
      post :subscribe
      post :unsubscribe
    end
  end

  resources :users

  root :to => "photos#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :photo
  belongs_to :user

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :photo, :counter_cache => true
  belongs_to :user
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_many :comments
  belongs_to  :user

  validates_presence_of :title

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

  has_many :likes
  has_many :like_users, :through => :likes, :source => "user"

  has_many :subscriptions
  has_many :subscription_users, :through => :subscriptions, :source => "user"

  def can_edit_by_user?(user)
    user && self.user == user
  end

  def find_like_by_user(user)
    user && self.likes.where( :user_id => user.id ).first
  end

  def find_subscription_by_user(user)
    user && self.subscriptions.where(:user_id => user.id).first
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :photo
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]

  has_many :comments
  has_many :photos

  has_many :photos

  has_many :likes
  has_many :like_photos, :through => :likes, :source => "photo"

  has_many :subscriptios
  has_many :subscriptios_photos, :through => :subscriptios, :source => "photo"
  # has_many :subscribed_photos, :through => :subscriptions, :source => "photo"


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  #helper_method 宣告給view 用
  helper_method :current_user

  protected

  def set_photo
    @photo = Photo.find( params[:photo_id] )
  end

  ### devise 本身就有current_user 這個方法  ### 覆寫!!
  # def current_user
  #   if session[:user_id]
  #     User.find( session[:user_id] )
  #   else
  #     nil
  #   end
  # end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_photo

  def create
    @comment = @photo.comments.build( comment_params )
    @comment.user = current_user

    @comment.save!
    #@comment.notify!

    respond_to do |format|
      format.html{ redirect_to root_url }
      format.js{ render :template => "comments/create" }
    end
  end

  def destroy
    @comment = @photo.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      # format.html { redirect_to root_url }
      format.js{ render :template => "comments/destroy" }
    end
  end

  protected

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_photo

  def create
    # using Ajax to like
    existing_like = @photo.find_like_by_user(current_user)

    unless existing_like
      @like = Like.create(:user => current_user, :photo => @photo)
    end

    respond_to do |format|
      format.html{ redirect_to :back }
      format.js{
        @photo.reload
        render :template => "likes/reload"
      }
    end
  end

  def destroy
    # using Ajax to dislike
    @like = current_user.likes.find( params[:id] )
    @like.destroy
    @like = nil

    respond_to do |format|
      format.html { redirect_to :back }
      format.js {
        @photo.reload
        render :template => "likes/reload"
      }
    end
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  before_action :set_photo, :only => [:show]
  before_action :set_my_photo, :only => [:edit, :update, :destroy]

  def index
    @photos = Photo.all.order("id DESC")
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    if @photo.save
      flash[:notice] = "Photo was successfully created."
      redirect_to photos_path
    else
      render :action => :new
    end
  end

  def show
    @page_title = @photo.title
  end

  def edit

  end

  def update
    if @photo.update(photo_params)
      flash[:notice] = "Photo was successfully updated."
      redirect_to photo_path
    else
      render :action => :edit
    end
  end

  def destroy
    @photo.destroy

    flash[:alert] = "Photo was successfully deleted."

    redirect_to photos_path
  end

  def subscribe
    @photo = Photo.find(params[:id])
    existing_subscription = @photo.find_subscription_by_user(current_user)
    unless existing_subscription
      @subscription = Subscription.create(:user => current_user, :photo => @photo)
    end

    redirect_to :back
  end

  def unsubscribe
    @photo = Photo.find(params[:id])
    existing_subscription = @photo.find_subscription_by_user(current_user)

    existing_subscription.destroy
    redirect_to :back
  end

private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_my_photo
    @photo = current_user.photos.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :description, :pic)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])

  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/comments/_comment.html.erb
<%= simple_format comment.content %>

app/views/comments/create.js.erb
$("#photo-comments-<%= @photo.id %> ul").append("<li id='<%= @comment.id %>'><%= j(render :partial => "comment", :locals => { :photo => @photo, :comment => @comment } ) %></li>");
// $("#photo-comments-<%= @photo.id %> ul").append("<li><%= j(render :partial => "comment", :locals => { :photo => @photo, :comment => @comment } ) %></li>");
$("#new_comment").trigger("reset");

app/views/comments/destroy.js.erb
// $("#photo-comments-<%= @photo.id %> ul").remove("<li class='<%= @comment.id %>'><%= j(render :partial => "comment", :locals => { :photo => @photo, :comment => @comment } ) %></li>");
$("#<%= @comment.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniPhotoForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="background container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

       <% if current_user %>

        Hi, <%= link_to current_user.name, user_path(current_user) %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %> |

      <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %> |
        <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
      <% end %>

    <%= yield %>

<br><br><br><br><br>
    <footer style="color: red">
      <p>------------footer---------<br>
        email: admin@aaa.aaa <br>
        password: 12345678
      </p>
    </footer>
  </div>

</body>
</html>

app/views/likes/_show.html.erb
<%= photo.likes_count %> peoples like.

<% photo.like_users.each do |u| %>
  <%= link_to u.name, user_path(u) %>
<% end %>
<br>
<% if like %>
  <%= link_to "[Dislike]", photo_like_path(photo, like), :method => :delete, :remote => true %>
<% else %>
  <%= link_to "[Like]", photo_likes_path(photo), :method => :post, :remote => true %>
<% end %>

app/views/likes/reload.js.erb
$("#photo-like-<%= @photo.id %>").html("<%= j(render :partial => "show", :locals => { :photo => @photo, :like => @like } ) %>");

app/views/photos/_form.html.erb
<% if @photo.errors.any? %>
      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<%= f.label :title, "Title" %>
    <%= f.text_field :title %>
<br>
<br>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
<br>
<br>
<div class="form-group">
  <%= f.label :pic, "Upload File" %>
  <%= f.file_field :pic %>
  <%= check_box_tag "destroy_photo", "1" %> 刪除檔案
</div>

app/views/photos/edit.html.erb
<h1>edit.html</h1>

<%= form_for @photo, :url => photo_path do |f| %>


  <%= render :partial => 'form', :locals => { :f => f } %>
  <br>
  <p>
    Origin Image
  </p>
  <%#= image_tag( @photo.pic(:medium) ) %>
  <%= link_to image_tag(@photo.pic.url(:medium)), @photo.pic.url, :target => "_blank" %>

  <br>
  <br>
  <%= f.submit "Update" %>
  <%= link_to 'Cancel', photos_path, :class => "btn btn-danger" %>

<% end %>

app/views/photos/index.html.erb
<h1>photos/index.html</h1>
<%#= current_user || 'not login'%>

  <%#= link_to 'new photo', new_photo_path, :class => "btn btn-danger" %>
  <%= button_to 'New Post', new_photo_path, :method => 'get', :class => "btn btn-danger" %>

  <br>
<% @photos.each do |photo| %>
  <div>
    <%= link_to photo.title, photo_path(photo)  %>

      <% if photo.can_edit_by_user?(current_user) %>
        <div class="photos-edit pull-right">
        <%#= link_to 'Edit', :controller => 'photos', :action => 'edit', :id => photo, :class => "text-right" %>
        <%= link_to 'Edit', edit_photo_url(photo) %>

        <%#= l  ink_to 'Delete', :controller => 'photos', :action => 'destroy', :id => photo , :class => "pull-right", :data => {:confirm => "r u sure?"}, :method => :delete %>
        <%= link_to 'X', photo_path(photo), :data =>{:confirm => "r u sure?"}, :method => :delete %>
        <br>
        </div>
      <% end %>

  </div>
  <%#= photo.pic %>
  <%#= link_to image_tag(photo.pic.url(:medium)), photo.pic.url, :target => "_blank" %>
  <%= link_to image_tag(photo.pic.url(:medium)), edit_photo_url(photo) %><br> <br>
  <%= photo.description %>
  <ul>
    <%#= link_to 'Show', :controller => 'photos', :action => 'show', :id => photo %>
    <%#= button_to 'Show', photo_path(photo), method: :get %>
    <%#= link_to 'Edit', :controller => 'photos', :action => 'edit', :id => photo %>
    <%#= link_to 'Edit', edit_photo_url(photo) %>
    <!-- <%#= link_to 'Delete', :controller => 'photos', :action => 'destroy', :id => photo %><br> -->
    <%#= button_to 'Delete', photo_path(photo), :data => {:confirm => "r u sure?"}, :method => :delete %>
  </ul>

  <!-- <p><%= photo.likes_count %>'s people like this.</p> -->
  <%# photo.like_users.each do |u| %>
    <%#= link_to u.name, user_path(u) %>
  <%# end %>

  <%# like = photo.find_like_by_user(current_user) %>

  <%# if like %>
    <%#= link_to "DisLike", photo_like_path(photo, like), :method => :delete %>
  <%# else %>
   <%#= link_to "Like", photo_likes_path(photo), :method => :post %>
  <%# end %>

  <!-- using ajax to like/dislike -->
  <div id="photo-like-<%= photo.id %>">
    <% like = photo.find_like_by_user(current_user) %>
    <%= render :partial => "likes/show", :locals => { :photo => photo, :like => like } %>
  </div>

<div class="clearfix"></div>

<!-- subscribe/unsubscripbe -->
  <div id="photo-subscribe-<%= photo.id %>">
    <% subscribe = photo.find_subscription_by_user(current_user) %>
    <% if subscribe %>
      <%= link_to "[Unsubscribe]", unsubscribe_photo_path(photo), :method => :post %>
    <% else %>
      <%= link_to "[Subscribe]", subscribe_photo_path(photo), :method => :post %>
    <% end %>
  </div>

  <div id="photo-comments-<%= photo.id %>">
    <ul>
    <% photo.comments.each do |comment| %>
      <li id="<%= comment.id %>">
        <%= comment.content %>

        <%= link_to comment.user.name, user_path(comment.user) %>
        <div class="pull-right">
          <%= link_to 'X', photo_comment_path(photo, comment), method: :delete, remote: true %>
          <%= comment.created_at.to_s(:short) %>
        </div>
      </li>
    <% end %>
    </ul>
  </div>

  <%= form_for Comment.new, :remote => true, :url => photo_comments_path(photo) do |f| %>
    <%= f.text_area :content %>
    <%= f.submit %>
  <% end %>

<% end %>

app/views/photos/new.html.erb
<h1>new html</h1>

<%= form_for @photo, :url => photos_path do |f| %>

<%= render :partial => 'form', :locals => { :f => f } %>
<br>
<br>
<%= f.submit "Create" %>
<br>
<%= link_to 'back to index', photos_path %>

<% end %>

app/views/photos/show.html.erb
<h1>show.html</h1>

<%= @photo.title %>
<br>
<%#= image_tag( @photo.pic(:medium) ) %>
<%= link_to image_tag(@photo.pic.url(:medium)), @photo.pic.url, :target => "_blank" %>
<br>
<%= simple_format(@photo.description) %>


<% like = @photo.find_like_by_user(current_user) %>
  <!-- using ajax to like/dislike -->
  <div id="photo-like-<%= @photo.id %>">
    <%= render :partial => "likes/show", :locals => { :photo => @photo, :like => like } %>
  </div>

  <div id="photo-comments-<%= @photo.id %>">
    <ul>
    <% @photo.comments.each do |comment| %>
      <li>
        <%= comment.content %>
 <!-- 這行會壞掉 -->
        <%#= link_to comment.user.name, user_path(comment.user) %>
        <div class="pull-right">
          <%= comment.created_at.to_s(:short) %>
        </div>
      </li>
    <% end %>
    </ul>
  </div>


<%= link_to 'Back to index', photos_path %>
<%#= @user.name %>



  <%# @user.like_photos.each do |photo| %>
   <%#= photo.title %>
  <%# end %>